
nginx:
  # build: ./nginx
  image: nginx-sr-local
  links:
    # - server-john
    # - server-paul
    # - server-george
    # - server-ringo
    - server-socket-rtc
  ports:
  #  - "3000:80"
   - "3001:80"

# server-john:
#   build: ./server
#   links:
#     - redis
#   expose:
#     - "3000"
#   environment:
#     - NAME=John

# server-paul:
#   build: ./server
#   links:
#     - redis
#   expose:
#     - "3000"
#   environment:
#     - NAME=Paul

# server-george:
#   build: ./server
#   links:
#     - redis
#   expose:
#     - "3000"
#   environment:
#     - NAME=George

# server-ringo:
#   build: ./server
#   links:
#     - redis
#   expose:
#     - "3000"
#   environment:
#     - NAME=Ringo

server-socket-rtc:
  # build: .
  image: socket-rtc-local
  links:
    - redis
  expose:
    - "4001"
  environment:
    - NAME=server-socket-rtc

redis:
  image: redis:alpine
  expose:
    - "6379"
